# vvv added while working on tinyx86 vvv #

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-tinyx86.json"

# ^^^ added while working on tinyx86 ^^^ #
